logging:
  level:
    web: debug

spring:
  datasource:
    url: jdbc:h2:mem:student
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
